global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: '/metrics'
    scheme: https
    static_configs:
      - targets: ['textcat-app-production-0e37.up.railway.app']
